name: run_cursor_task
on:
  project_card:
    types: [moved]

jobs:
  cursor-run:
    if: github.event.project_card.column_name == 'In-Progress'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Cursor + GUI deps)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk-3-dev curl unzip
          npm install -g vibe-tools
          Xvfb :99 -screen 0 1920x1080x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run Cursor Agent (※暫定：echo のみ)
        run: |
          echo "ここに cursor agent 実行を入れる（後日Xvfb + VNC対応予定）"
