name: run_cursor_task
on:
  issues:
    types: [labeled]

jobs:
  cursor-run:
    if: github.event.label.name == 'In-Progress'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simulate cursor execution
        run: echo "📘 Triggered by In-Progress label!"